### PR TITLE
Initial Commit of all the files forked from the Rest Module:

### PR DESCRIPTION
**Pull request by gaurav-handysolver**
https://github.com/humhub/rest

It will serve as a base for us to build the custom end-points.

#1

### CODE REVIEW

**Comment by donni106** [comment]
big thanks for starting here.
first question, is forking the rest module the best way? regarding the future we will also need to update core features as mentioned in #1. could this work and does this fit well in a fork of the rest module?
second question, does it work to have the new forked module installed next to the original rest module in the same HumHub instance? how will future updates of the original rest module affect that setup? what if our new module is not a fork but a completely new module on top of existing rest apis, that will require an installed rest module? i guess that way less conflicts can happen? what is your opinion?

---

please create an own pull request for the commit `Issue Resolved : Add registration endpoint.` that relates to issue #2 and could be reviewed independently on its own with just the changes made for that topic.

**Comment by handysolver** [comment]
Hi @donni106,

Thanks for the detailed review.

We forked the Rest module because it has many functions already in place that allows us to build on.
The fork was: https://github.com/gaurav-handysolver/smart-village-humhub-api
Initial idea was that we can add features in an isolated way (not update core files). So we can rebase future updates made to the original Rest module repo without many conflicts.

Currently having both modules active in Humhub does not work. This is because namespace conflicts or similar might be happening. We can investigate this if we want to keep both modules. Else our new module has all the API endpoints of the original Rest module too.

For future Pull requests, we will create a branch for each issue (issue-1, issue-2 etc).
After a pull request is merged into the main branch, the issue branch can be autodeleted.
We will follow the directions you mentioned for the pull requests and commit messages.

If you prefer we can delete the current branch (staging) and pull request already made. And create new ones.

Look forward to hearing from you.
Thanks,
Rahul

**Comment by donni106** [comment]
> For future Pull requests, we will create a branch for each issue (issue-1, issue-2 etc).
> After a pull request is merged into the main branch, the issue branch can be autodeleted.
> We will follow the directions you mentioned for the pull requests and commit messages.

👍 

> If you prefer we can delete the current branch (staging) and pull request already made. And create new ones.

yes, let's finish the base module in the most useful way first, before creating several pull requests for all the features.

> We forked the Rest module because it has many functions already in place that allows us to build on.
> Initial idea was that we can add features in an isolated way (not update core files). So we can rebase future updates made to the original Rest module repo without many conflicts.
>
> Currently having both modules active in Humhub does not work. This is because namespace conflicts or similar might be happening. We can investigate this if we want to keep both modules.

having a fork of the rest module seems not very sustainable to me. there are a few things i need to think of. first are test scenarios: having a HumHub instance, i do not want to uninstall a rest module and install a new module to test it and then uninstall the new module and reinstall the rest module if something is not working. another case is the regularly updates of the rest module. we want to use the auto update functions of HumHub to update modules, especially the rest module. if we exchange it with a new module, we loose the auto updates, which can result in different problems across different responsibilities. a third thing will be updates to the core and web somewhen. i do not think that this could go well in a fork of the rest module.
let's always talk about approaches and ideas, before developing something. we would like to use a default HumHub instance, that can be updates with different modules with all of its benefits. additionally we want a "Smart Village App" module that extends the api first and more later. couldn't this be achieved with an "empty" module, that requires the rest module installed to work, that gets new api endpoints next to the existing ones. some drawing, what about that:

Bildschirmfoto 2022-04-22 um 11 35 11

isn't this possible? multiple modules that create the api all together?

**Comment by handysolver** [comment]
Hi @donni106,
Thanks for discussing further.

So, we can create a new empty module from scratch for "Smart Village App". 
It can have the dependency, that to work it requires the Rest module to be installed. Then I assume we can extend/use the classes and functions of the Rest module as required.

This can be cleaner as well as it will not have all the Rest module code and only our code for the new endpoints.

The only drawback can be that.. an update of the Rest module might cause a break in the "Smart Village App". Since it will be dependent on the Rest module's code. 
So to get around this we might need to execute prewritten test cases on each update to ensure that our module is continuing to work properly.

The other approach is if we don't want any dependency, then we continue on the replicated codebase.

Finally, as you mentioned any fix/ feature request or issue that you think is appropriate for being applied on a fork of the Rest module.. can be done. This way we can contribute back to the community as pointed out.

Thanks Daniel. Looking forward to your response.

**Comment by handysolver** [comment]
Good Morning @donni106,
I was wondering if you have an update for us as per our last discussion. We can accordingly proceed.

Thanks

**Comment by donni106** [comment]
> So, we can create a new empty module from scratch for "Smart Village App".
> It can have the dependency, that to work it requires the Rest module to be installed. Then I assume we can extend/use the classes and functions of the Rest module as required.
>
> This can be cleaner as well as it will not have all the Rest module code and only our code for the new endpoints.

yes, let's do it this way please. all the new things can be created as new endpoints in our module.

> The only drawback can be that.. an update of the Rest module might cause a break in the "Smart Village App". Since it will be dependent on the Rest module's code.
> So to get around this we might need to execute prewritten test cases on each update to ensure that our module is continuing to work properly.

for now we do not need the written test cases. i do not know yt how we could integrate that in ours workflows. we can talk about that at some later point. we have a staging system, where we will update the rest module first and then try to call our new endpoints. if everything works, this can be done on production as well. if there are problems, we need to fix them, bevor upgrading on production. i think this is straight forward and for the beginning the best approach.

> Finally, as you mentioned any fix/ feature request or issue that you think is appropriate for being applied on a fork of the Rest module.. can be done. This way we can contribute back to the community as pointed out.

i agree on this and hope it will work out. i know that these guys are busy. so PRs we create could take some time to be merged. but sooner or later they will. to bridge that times and to remain independent, we could think of creating temporary endpoints in our module that provide the necessary functionality already and can be deleted once the PRs are merged. one example: we want to extend the conversation API to provide information about the read/unread status. this would be a change in the REST module and need approval and merge from them. in the meantime we could provide a api/v1/temp/mail endpoint from our module that is already useable and will eventually become obsolete. 
what's your opinion about that workflow?

**Comment by handysolver** [comment]
Hi @donni106,
Thanks for getting back in detail.
As discussed, we will move forward with a new module for our endpoints. It can be dependent on the current REST module.

Also, we can create temporary endpoints in our module.. which might get obsolete if the equivalent functionality pull requests on the REST module get accepted.

We will update you soon.

Thanks,
Rahul

**Pull request closed without merging**
